In [57]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [40]:
#Load the data from the CSV files
fake_news = pd.read_csv('Fake.csv')
fake_news.isnull().any()

title      False
text       False
subject    False
date       False
dtype: bool

In [41]:
true_news = pd.read_csv('True.csv')
true_news.isnull().any()

title      False
text       False
subject    False
date       False
dtype: bool

In [42]:
#Load the data into dataframes
df_fake = pd.DataFrame(fake_news)
df_fake

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016"
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016"
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016"
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016"
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016"

In [43]:
df_true = pd.DataFrame(true_news)
df_true

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017"
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017"
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017"
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017"

In [44]:
labels = []

for i in range(0, len(df_fake)):
    labels.append(1)

In [45]:
df_fake['label'] = labels
df_fake

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",1
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",1
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",1
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",1
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",1
...,...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",1
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",1
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",1
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",1
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",1

In [46]:
labels = []

for i in range(0, len(df_true)):
    labels.append(0)

In [47]:
df_true['label'] = labels
df_true

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",0
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",0
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",0
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",0
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",0
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",0
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",0
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",0
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",0
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",0

In [48]:
#Merge the two dataset into one
frames = [df_fake, df_true]
result = pd.concat(frames)
result

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",1
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",1
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",1
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",1
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",1
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",0
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",0
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",0
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",0
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",0

In [49]:
#Shuffle the rows of the new dataframe
final_df = result.sample(frac=1).reset_index(drop=True)
final_df

,title,text,subject,date,label
0,UK says defense commitment in Nordic and Balti...,LONDON (Reuters) - Britain will pledge on Mond...,worldnews,"September 3, 2017",0
1,Ted Cruz’s Daughter Reveals A Shocking Family...,Ted Cruz got a brutal lesson in why he should ...,News,"April 14, 2016",1
2,New Poll Has Very Bad News For The NRA (DETAILS),While it may not come as much of a surprise th...,News,"April 25, 2017",1
3,NYC MAYOR DE BLASIO…Putting Illegal Aliens Bef...,CNN s Jake Tapper asked New York City Mayor Bi...,left-news,"Feb 6, 2017",1
4,Turkey calls on citizens to leave northern Ira...,ANKARA (Reuters) - Turkey called on its citize...,worldnews,"September 28, 2017",0
...,...,...,...,...,...
44893,SYRIAN IMMIGRANT Who Said “9-11 Changed The Wo...,Feeling safer? One of the sitting members on t...,left-news,"Jun 14, 2016",1
44894,"WOW! BLACK DALLAS Police Sergeant Sues Obama, ...",Read the list of people and organizations this...,left-news,"Sep 18, 2016",1
44895,Lifetime Republican Voter Thanks President Ob...,"Republican lawmakers hate Obamacare, but it s ...",News,"March 4, 2016",1
44896,CLASS ACT! WATCH THE TODAY SHOW’S MATT LAUER G...,,left-news,"Feb 15, 2017",1
44897,Uganda police arrest youths who oppose fresh t...,KAMPALA (Reuters) - Ugandan police have arrest...,worldnews,"September 18, 2017",0

In [50]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    44898 non-null  object
 1   text     44898 non-null  object
 2   subject  44898 non-null  object
 3   date     44898 non-null  object
 4   label    44898 non-null  int64
dtypes: int64(1), object(4)
memory usage: 1.7+ MB

In [58]:
x = final_df.drop('label', axis=1)
y = final_df['label']

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.9)

In [66]:
x_train

,title,text,subject,date
42475,"At least 61 dead, 300 injured by quake in Iran...",DUBAI (Reuters) - At least 61 people were kill...,worldnews,"November 12, 2017"
40680,HILLARY TO OBAMA: “call off your f–king dogs”,"According to insider, and author Edward Klein,...",left-news,"Mar 9, 2016"
17405,Momentum grows for another grand coalition in ...,BERLIN (Reuters) - Members of Germany s Social...,worldnews,"November 25, 2017"
26157,UNREAL! BLACK TRUMP SUPPORTER Threatened And A...,This guy is awesome! He is so right and so on ...,politics,"May 29, 2016"
17408,"Fearing far-right surge, Merkel tells Germans ...",BERLIN (Reuters) - Fears in Germany that vote...,worldnews,"September 21, 2017"
...,...,...,...,...
12499,"Exclusive: 'If there's a shutdown, there's a s...",WASHINGTON (Reuters) - President Donald Trump ...,politicsNews,"April 28, 2017"
19476,ANOTHER Poll Has Clinton Beating Trump By 15 ...,"Last week, RABA Research had Hillary Clinton b...",News,"August 5, 2016"
34753,"White Men Threw Eggs, Shouted Racial Slurs At...","On Friday, St. Louis police arrested two 30-ye...",News,"June 27, 2016"
25910,Fox News Confuses Julius Caesar Depiction For...,Fox News loves to point the finger at Snowfla...,News,"June 12, 2017"
22950,"Not in a hallway, not in a text: committee war...","WASHINGTON (Reuters) - A single, short electro...",politicsNews,"August 1, 2017"

In [67]:
y_train

42475    0
40680    1
17405    0
26157    1
17408    0
        ..
12499    0
19476    1
34753    1
25910    1
22950    0
Name: label, Length: 4489, dtype: int64